version: 2
jobs:
  do_SendInfo:
    docker:
      - image: najahi/oven:latest
    environment:
      is_test: false
    steps:
      - run: git clone https://github.com/chips-project/msm-4.14 --depth=1 -b pie .
      - run: echo 'export device="<b>Xiaomi Redmi Note 8/8T</b> (Ginkgo/Willow) Android 9.0/Pie"' >> $BASH_ENV
      - run: wget https://raw.githubusercontent.com/najahiiii/Noob-Script/noob/ci/circle/sendInfo
      - run: chmod +x sendInfo
      - run: bash sendInfo
  do_Bake1:
    docker:
      - image: najahi/oven:latest
    working_directory: ~/do_Bake1
    environment:
      is_test: false
    steps:
      - run: git clone https://github.com/chips-project/msm-4.14 --depth=1 -b pie .
      - run: wget https://raw.githubusercontent.com/najahiiii/Noob-Script/noob/ci/circle/do_ginkgo
      - run: chmod +x do_ginkgo
      - run: bash do_ginkgo
workflows:
  version: 2
  Continuous-HotOven:
    jobs:
      - do_SendInfo
      - do_Bake1:
          requires:
            - do_SendInfo
